### ISSUE TITLE
Detect for every frame

### ISSUE THREAD

**Issue by awl-an-dang** [AIHunters/AcurusTrack#12]
Does it need to detect for every frame for tracking? If yes, in case of missing bounding boxes, how the algorithm handles it. Could you please send the workflow of how algorithm work. Many thanks. Amazing work :D

**Comment by vishneuskaja** [comment]
Hi there!👋🏼
The algorithm can work (and actually works) with the frames with missing bounding boxes. The only question is, for how long an object has been away from a frame. If the pause is not very long, and the nature of movement hasn't changed considerably then the algorithm handles OK. We are considering a movement and a sort of trajectory probability.

![image](https://user-images.githubusercontent.com/70645285/104644577-f9397780-56be-11eb-9c2e-e81c4834b308.png)

Please see the workflow of how AcurusTrack works above.

And thanks for your review!
