### ISSUE TITLE
Tracking individuals in the scene

### ISSUE THREAD

**Issue by TalBarami** [AIHunters/AcurusTrack#13]
Hello and thanks for publishing this wonderful repository.
I'm using Openpose in my research project to extract skeletons of individuals from a short video clip.
I need a tracking tool to identify the location of each individual over time.
I was hoping to fill a 'person_id' field of each skeleton in the json output from Openpose with the id from your output, but I'm not quite sure how to match your output with openpose.

Also, I was unable figure how to extract the pose instead of face. I tried to set the logic param 'face_or_pose_meta' to 'pose' and created an openpose json file as an input to people_in_masks_demo.py
However, when I try to execute the code I get a division by zero error:
`
Traceback (most recent call last):
  File "C:\Users\TalBarami\.conda\envs\openpose\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\TalBarami\.conda\envs\openpose\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\research\AcurusTrack\pipeline.py", line 297, in window_processing
    wind_obj.algo_iteration()
  File "C:\research\AcurusTrack\track\tracker.py", line 73, in algo_iteration
    self.internal_loop()
  File "C:\research\AcurusTrack\track\tracker_merger.py", line 75, in internal_loop
    accepted_count = self.acc_obj.analyse_acceptance(self.change_track)
  File "C:\research\AcurusTrack\track\tracker.py", line 288, in analyse_acceptance
    self.curr_acceptance = self.get_acceptance(change_track)
  File "C:\research\AcurusTrack\track\tracker.py", line 322, in get_acceptance
    ratio = self.compute_ratio(pair, change_track)
  File "C:\research\AcurusTrack\track\tracker.py", line 385, in compute_ratio
    lkls_ratio = self.likelihoods_multiplication(lkls_new_diff_curr, lkls_curr_diff_new)
  File "C:\research\AcurusTrack\track\tracker.py", line 350, in likelihoods_multiplication
    power = values / len(curr_diff_new)
ZeroDivisionError: division by zero
`
It looks like 'curr_diff_new' is empty, but I couldn't figure out why.
Your help will be very appreciated, thanks again!

**Comment by KseniaMeshkova** [comment]
Hello!
Thanks for the appreciation!
I have several assumptions about why your processing performs this way, but it would be best for me to see your JSON example and the video you’re trying to process (if it’s acceptable). This way I will tell for sure. Thanks

**Comment by TalBarami** [comment]
Hey, thanks for the quick reply. I actually managed to solve this issue by changing the json format to look like this:
{
    "0": [{
            "person": [[729.354, 196.498, 0.797851], [778.345, 194.456, 0.784372], [758.694, 194.509, 0.633028], [758.633, 245.403, 0.141013], [727.275, 245.38, 0.16468], [805.628, 194.457, 0.85464], [839.069, 247.391, 0.867987], [803.75, 290.464, 0.765151], [776.326, 321.734, 0.799415], [758.623, 319.857, 0.776126], [756.664, 411.891, 0.818282], [746.996, 496.132, 0.836269], [797.842, 321.792, 0.732091], [794.005, 415.782, 0.86193], [794.007, 503.96, 0.806805], [723.406, 194.395, 0.241742], [731.295, 190.509, 0.756347], [0.0, 0.0, 0.0], [752.827, 176.748, 0.686993], [792.035, 525.569, 0.822497], [807.63, 523.651, 0.832861], [791.963, 509.889, 0.714373], [713.654, 517.694, 0.777005], [713.626, 509.859, 0.805231], [758.669, 507.988, 0.897312]]
        }, {
            "person": [[570.525, 169.026, 0.890233], [556.85, 202.328, 0.883957], [527.514, 210.069, 0.853381], [509.801, 259.072, 0.944459], [541.211, 290.504, 0.88133], [586.232, 196.498, 0.884879], [592.155, 249.289, 0.284127], [602.0, 290.437, 0.284577], [574.519, 313.989, 0.794122], [556.835, 317.908, 0.815591], [566.693, 394.299, 0.815324], [570.527, 474.57, 0.821117], [596.044, 310.04, 0.739371], [617.551, 382.561, 0.955028], [574.593, 447.258, 0.818767], [557.002, 164.99, 0.953311], [572.523, 163.121, 0.940356], [541.253, 165.162, 0.856181], [0.0, 0.0, 0.0], [600.004, 478.567, 0.602404], [601.907, 474.634, 0.59656], [570.526, 451.147, 0.425552], [597.988, 492.279, 0.835699], [584.284, 494.243, 0.744565], [564.712, 478.631, 0.691609]]
        }, {
            "person": [[960.505, 147.382, 0.890468], [989.853, 194.367, 0.875529], [942.873, 196.405, 0.854126], [930.989, 266.961, 0.858733], [919.356, 329.657, 0.792028], [1034.89, 190.499, 0.766307], [1042.81, 259.146, 0.440947], [1040.8, 298.282, 0.160284], [983.986, 319.896, 0.763493], [954.61, 319.902, 0.757693], [964.414, 425.658, 0.835755], [978.052, 509.88, 0.878431], [1013.35, 319.876, 0.78762], [1025.17, 427.517, 0.868206], [1032.99, 511.824, 0.784067], [950.754, 137.641, 0.806347], [966.345, 135.648, 0.862808], [0.0, 0.0, 0.0], [991.852, 139.588, 0.713246], [1034.94, 541.198, 0.752551], [1044.76, 539.236, 0.776182], [1027.1, 521.649, 0.699435], [972.211, 539.194, 0.867489], [962.349, 535.339, 0.889964], [983.963, 519.635, 0.759294]]
        }, {
            "person": [[292.374, 165.15, 0.863581], [247.352, 194.449, 0.839219], [225.839, 194.512, 0.867615], [196.33, 259.086, 0.928978], [235.623, 306.199, 0.831856], [272.785, 194.455, 0.77166], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [272.714, 331.548, 0.749037], [247.351, 333.527, 0.711049], [243.441, 419.754, 0.86435], [196.376, 504.009, 0.828685], [290.447, 327.645, 0.745682], [294.345, 417.784, 0.837377], [294.351, 509.887, 0.843103], [290.382, 159.173, 0.800787], [300.213, 163.002, 0.316656], [268.887, 149.447, 0.65686], [0.0, 0.0, 0.0], [337.44, 523.58, 0.857071], [335.497, 517.743, 0.761934], [288.417, 523.652, 0.839049], [210.146, 535.335, 0.800052], [194.526, 529.496, 0.801937], [186.604, 507.852, 0.710916]]
        }, {
            "person": [[1103.4, 131.712, 0.851872], [1136.81, 178.738, 0.880025], [1072.07, 176.82, 0.79783], [1021.16, 257.053, 0.809363], [966.384, 331.568, 0.779024], [1203.44, 178.828, 0.763426], [1244.58, 268.873, 0.803293], [1264.16, 353.105, 0.833831], [1117.2, 374.72, 0.662177], [1074.03, 368.866, 0.693315], [1083.93, 509.901, 0.638625], [1089.75, 635.204, 0.726884], [1154.48, 380.587, 0.644014], [1132.91, 513.818, 0.643496], [1119.12, 617.574, 0.538883], [1091.81, 116.132, 0.848207], [1117.23, 118.073, 0.884047], [0.0, 0.0, 0.0], [1150.51, 119.98, 0.720499], [1136.77, 660.738, 0.43526], [1144.64, 650.943, 0.510345], [1113.3, 619.638, 0.238798], [1115.25, 676.415, 0.681513], [1091.76, 674.453, 0.659756], [1085.81, 643.092, 0.482659]]
        }
    ],
    "1": [{
            "person": [[729.238, 196.482, 0.718883], [774.415, 192.449, 0.78068], [754.779, 192.463, 0.588912], [756.698, 243.443, 0.0868057], [739.073, 268.889, 0.0915376], [793.985, 192.442, 0.815577], [836.971, 243.453, 0.915337], [795.901, 290.374, 0.756338], [774.423, 317.851, 0.788598], [758.595, 315.915, 0.744362], [754.79, 402.157, 0.817752], [745.057, 492.256, 0.872503], [792.062, 317.903, 0.758972], [792.002, 411.848, 0.864862], [792.059, 502.028, 0.813114], [717.546, 194.435, 0.185224], [729.295, 190.528, 0.737312], [0.0, 0.0, 0.0], [745.072, 176.776, 0.68939], [790.009, 523.657, 0.88548], [805.617, 523.558, 0.864733], [790.057, 509.903, 0.680303], [711.637, 509.939, 0.790287], [711.613, 507.821, 0.767967], [756.744, 505.887, 0.795977]]
        }, {
            "person": [[570.595, 165.107, 0.95779], [556.936, 198.387, 0.909542], [527.514, 206.194, 0.838647], [509.836, 257.091, 0.937269], [539.252, 288.443, 0.866302], [588.152, 196.362, 0.924587], [599.979, 243.5, 0.524307], [604.0, 286.561, 0.407225], [574.545, 308.148, 0.806826], [556.818, 313.977, 0.811085], [562.802, 390.337, 0.797077], [568.637, 472.601, 0.820347], [597.993, 306.151, 0.78823], [617.645, 378.588, 0.913628], [586.355, 453.043, 0.871177], [558.899, 161.159, 0.904445], [572.625, 161.076, 0.895542], [543.172, 163.137, 0.853287], [0.0, 0.0, 0.0], [617.544, 480.516, 0.857518], [617.55, 476.599, 0.88176], [582.331, 460.812, 0.576273], [596.081, 492.159, 0.814141], [584.271, 492.322, 0.767022], [560.785, 478.493, 0.779497]]
        }, {
            "person": [[952.669, 145.427, 0.853056], [982.054, 190.516, 0.850415], [936.939, 194.495, 0.864085], [923.28, 261.1, 0.807834], [917.283, 323.746, 0.854468], [1027.11, 180.849, 0.841967], [1040.74, 257.118, 0.426355], [1040.79, 304.104, 0.113548], [980.163, 319.853, 0.775171], [950.711, 319.832, 0.742719], [962.392, 417.857, 0.833381], [974.202, 507.865, 0.841845], [1011.34, 319.826, 0.802553], [1021.22, 417.76, 0.800687], [1027.07, 507.867, 0.818091], [948.671, 133.83, 0.881956], [962.454, 133.686, 0.914216], [0.0, 0.0, 0.0], [984.031, 135.645, 0.706564], [1029.03, 541.196, 0.728524], [1040.87, 539.195, 0.744736], [1025.07, 509.961, 0.614447], [968.286, 531.438, 0.802113], [958.489, 527.491, 0.836237], [980.133, 511.881, 0.808921]]
        }, {
            "person": [[1091.72, 129.759, 0.827865], [1132.88, 176.762, 0.829861], [1062.38, 169.01, 0.763466], [1011.45, 247.341, 0.843646], [962.503, 317.853, 0.822263], [1197.53, 178.735, 0.787572], [1232.84, 261.065, 0.789838], [1258.23, 351.096, 0.84951], [1105.41, 370.814, 0.68869], [1060.38, 368.782, 0.665083], [1074.03, 507.954, 0.748386], [1080.0, 625.453, 0.658832], [1148.58, 376.657, 0.649972], [1121.19, 507.837, 0.754829], [1107.42, 611.745, 0.66045], [1087.85, 112.189, 0.818671], [1107.44, 116.17, 0.880757], [0.0, 0.0, 0.0], [1146.61, 118.015, 0.673262], [1123.05, 648.967, 0.690159], [1134.76, 639.177, 0.736513], [1103.39, 617.649, 0.31835], [1105.47, 664.685, 0.651808], [1087.86, 664.689, 0.660703], [1074.12, 633.343, 0.544887]]
        }, {
            "person": [[292.424, 165.102, 0.84701], [251.26, 192.441, 0.790132], [227.787, 192.526, 0.837018], [198.429, 257.121, 0.873122], [241.456, 306.068, 0.867345], [272.843, 192.45, 0.749227], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [274.795, 323.737, 0.779736], [257.11, 325.756, 0.737961], [255.208, 415.821, 0.877502], [198.42, 494.17, 0.844271], [294.412, 321.747, 0.722888], [292.42, 415.867, 0.855386], [292.406, 507.898, 0.865469], [290.423, 157.259, 0.804021], [300.25, 159.178, 0.195625], [272.744, 149.41, 0.719525], [0.0, 0.0, 0.0], [335.451, 521.619, 0.80949], [333.545, 511.9, 0.7665], [286.52, 521.595, 0.825361], [212.183, 529.467, 0.776698], [198.389, 525.562, 0.797773], [190.5, 494.275, 0.75869]]
        }
    ],
    "2": [{
            "person": [[570.549, 163.179, 0.949495], [556.983, 196.428, 0.940888], [527.532, 200.355, 0.84552], [509.82, 255.139, 0.908784], [539.278, 286.513, 0.835839], [588.229, 194.436, 0.937584], [602.009, 241.507, 0.808683], [604.011, 286.469, 0.581873], [574.566, 306.219, 0.82232], [556.811, 311.969, 0.818174], [558.91, 386.436, 0.840902], [566.677, 464.87, 0.825389], [598.049, 306.07, 0.802214], [617.691, 378.562, 0.905807], [601.867, 456.984, 0.846516], [558.874, 157.254, 0.881167], [572.585, 155.272, 0.883909], [543.246, 161.188, 0.824391], [0.0, 0.0, 0.0], [631.317, 480.475, 0.818981], [631.345, 476.568, 0.848687], [590.18, 462.838, 0.763797], [594.086, 484.43, 0.784989], [582.333, 490.216, 0.787474], [558.906, 476.521, 0.832595]]
        }, {
            "person": [[948.667, 141.53, 0.894644], [978.144, 184.664, 0.910283], [932.992, 194.349, 0.897749], [917.343, 259.134, 0.906997], [915.374, 321.785, 0.827754], [1023.13, 180.775, 0.828629], [1032.96, 255.19, 0.360166], [1032.95, 300.248, 0.0844754], [978.141, 317.878, 0.752485], [948.714, 319.798, 0.744526], [958.518, 415.875, 0.826192], [966.339, 503.991, 0.835427], [1007.51, 315.901, 0.717376], [1011.51, 415.762, 0.861141], [1023.15, 505.91, 0.80419], [942.874, 133.696, 0.843068], [956.575, 131.757, 0.867165], [0.0, 0.0, 0.0], [979.98, 133.665, 0.799187], [1025.15, 535.312, 0.537199], [1029.13, 527.53, 0.571584], [1015.37, 509.871, 0.631305], [964.344, 525.593, 0.887657], [950.679, 525.462, 0.908977], [976.17, 509.865, 0.765393]]
        }, {
            "person": [[296.339, 163.183, 0.773124], [255.155, 190.503, 0.780306], [231.708, 190.499, 0.778601], [206.201, 255.225, 0.847023], [245.373, 304.203, 0.822166], [272.86, 192.437, 0.739153], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [274.853, 323.729, 0.769474], [259.042, 325.737, 0.740132], [263.034, 413.958, 0.866515], [206.189, 490.254, 0.815669], [294.364, 321.746, 0.732782], [292.377, 415.764, 0.867251], [290.502, 507.812, 0.861844], [292.416, 153.295, 0.738644], [304.162, 153.352, 0.287114], [272.881, 149.329, 0.741134], [0.0, 0.0, 0.0], [335.537, 515.764, 0.774895], [333.522, 509.899, 0.771337], [282.643, 519.628, 0.772758], [216.016, 525.617, 0.79714], [202.284, 523.585, 0.811155], [194.356, 490.316, 0.777775]]
        }, {
            "person": [[1087.85, 122.017, 0.797367], [1123.08, 172.903, 0.811508], [1058.44, 165.151, 0.833577], [1007.46, 241.544, 0.849681], [950.696, 312.036, 0.731474], [1187.77, 178.705, 0.761794], [1226.85, 261.033, 0.808479], [1244.62, 347.276, 0.872548], [1097.58, 368.81, 0.663107], [1056.38, 364.898, 0.679933], [1058.43, 505.919, 0.719421], [1074.14, 623.517, 0.747324], [1136.83, 372.745, 0.65295], [1117.21, 505.9, 0.750974], [1105.51, 613.692, 0.672734], [1081.97, 110.174, 0.720355], [1103.5, 114.141, 0.858417], [0.0, 0.0, 0.0], [1136.8, 117.983, 0.6617], [1117.19, 646.971, 0.651532], [1128.94, 637.25, 0.691703], [1103.4, 619.613, 0.408239], [1095.68, 660.687, 0.701406], [1076.11, 660.7, 0.725533], [1074.14, 635.221, 0.618999]]
        }, {
            "person": [[719.47, 196.464, 0.747559], [770.395, 186.621, 0.716785], [745.025, 188.595, 0.598971], [744.985, 241.403, 0.0859796], [721.479, 241.459, 0.060026], [790.086, 186.611, 0.822489], [827.257, 243.363, 0.885924], [790.073, 288.465, 0.743695], [774.259, 311.992, 0.741002], [754.72, 310.046, 0.699189], [748.93, 400.195, 0.82422], [744.933, 490.217, 0.861056], [790.083, 313.952, 0.7327], [789.991, 404.108, 0.840327], [790.08, 494.235, 0.854104], [711.61, 192.494, 0.175722], [721.448, 188.589, 0.726726], [0.0, 0.0, 0.0], [741.086, 172.89, 0.694192], [786.094, 519.672, 0.741919], [797.876, 517.706, 0.743779], [788.093, 505.936, 0.658148], [711.668, 507.891, 0.789027], [711.642, 500.044, 0.744005], [754.725, 498.108, 0.759947]]
        }
    ],
...

Is this the right structure?

**Comment by vishneuskaja** [comment]
@TalBarami did Ksenia manage to answer your question? Thanks!

**Comment by TalBarami** [comment]
@vishneuskaja yes, she did. Thanks a lot!

**Comment by TalBarami** [comment]
@KseniaMeshkova hey again Ksenia, I have encountered an error while executing the track on one of my jsons: apparently the code encounters an error when one of the frames contains no skeletons in the scene (which can happen when everyone leaves the room). Is there any way to overcome this issue?

Thanks again!

**Comment by KseniaMeshkova** [comment]
“Hey, try to set number_of_acc_for_acc=2, it’s preferable for pose and there are no errors. Nevertheless, it is possible that there is a bug in the code, which appears when number_of_acc_for_acc=1, and it would be easier to catch if you share the video. Thank you :)”

**Comment by vishneuskaja** [comment]
**@TalBarami here's the answer to your previous question**
> Edit: except this: my openpose does not output a "BigToes" joint. I have a left and a right joints. What do you mean when you specify BigToes?
> 
> Thanks!

We always took one point between the people’s feet. When a person’s moving, one foot is generally still and the other is moving. It would be too hard for Kalman filter to process such gaps. That’s why there’s the “BigToes” joint.

**Comment by TalBarami** [comment]
Sadly I'm unable to share the video because of medical confidentiality.
Changing the number_of_acc_for_acc to 2 didn't solve the issue for all of the cases, but it did help with some of them.
I can share more problematic json files (with their original resolution) if you find it interesting.
I have added the BigToes joint to my code, thanks!

**Comment by vishneuskaja** [comment]
Hi @TalBarami! Have you been able to fix the issues? 
Can we help you with something else?

**Comment by TalBarami** [comment]
Hello @vishneuskaja, I couldn't perform tracking on long videos but since I can't share the video (only it's openpose output) I guess I'll just stay tuned for an update.

Thanks for your help!
