### ISSUE TITLE
Online vs Offline Tracking approach

### ISSUE THREAD

**Issue by lstomy** [AIHunters/AcurusTrack#14]
Hi,

Appreciate your great work. I am curious is it online tracking approach or offline (post-processing of full sequence)? Seems that its offline solution or Am I wrong? I didnt run the code.

Thanks~

**Comment by vishneuskaja** [comment]
Hi! Thanks a lot for your review!
This approach is both offline and online.

What concerns the online in more detail:
1. In the case of online, there will be real-time processing. The processing of a potential window will take less than its length even on a weak CPU.
2. There will be some delays in decision-making. These delays will be determined by the length of a window. So this has to depend on the business case. In the case of online applications, the algorithm supports real-time processing. But the decision delay can make some of the cases impossible to handle.

Anyway, it’s more a question of the realization that the algorithm itself.

Hope I managed to answer your question! :)

**Comment by lstomy** [comment]
Okay, got it. Thanks for your kind explanation.
