### ISSUE TITLE
Result reproducibility

### ISSUE THREAD

**Issue by igormusinov** [AIHunters/AcurusTrack#16]
Hi

I'm trying to reproduce your result from here https://github.com/AIHunters/AcurusTrack/blob/master/examples/images/people_masks_occlusions_25_aihunters.gif  with default config.py from master but the tracks are different. 
Could you provide config.py for this result https://github.com/AIHunters/AcurusTrack/blob/master/examples/images/people_masks_occlusions_25_aihunters.gif , please. Or maybe another config.py , to reproduce another cool tracking example

How I get the results.
```
cd examples/people_in_masks_demo/
python people_in_masks_demo.py
cd ../..
python visualization/make_video_with_meta.py \
 --files_dir examples/people_in_masks_demo/results/people_masks_occlusions_part_1.mp4/dema_people_in_masks/result \
 --video_path examples/people_in_masks_demo/people_masks_occlusions_part_1.mp4 \
 --path_to_homography_dict examples/people_in_masks_demo/dict_with_homography_matrix.json \
 --name out
```

**Comment by vishneuskaja** [comment]
Hi! 
Could you share your JSON for us to see where the problem is? It would be easier like that. 
The thing is, there can be several optimal decisions. With your input, we will be able to tell if your output is good still.

**Comment by igormusinov** [comment]
https://drive.google.com/file/d/19Ku71-2vyEt3P5GclZqJK1ISZZFVzQd8/view?usp=sharing

here is **config.py** like https://github.com/AIHunters/AcurusTrack/blob/master/config.py
also **examples** folder like https://github.com/AIHunters/AcurusTrack/tree/master/examples

**Comment by vishneuskaja** [comment]
I was unable to access your example. Could you grant the access?
Thanks!

**Comment by igormusinov** [comment]
Hi @vishneuskaja ,  now opened )

**Comment by vishneuskaja** [comment]
Hi! Thanks for providing your output. We checked your case and noticed that the config use_final_merge  is set for False. 
That’s why you couldn’t merge the tracks. Please try setting this config for True and see what happens.

Also, the fixed coordinates system was off in your example.

Thanks for pointing these issues out, now we have added the additional config parameters for this case here: https://github.com/AIHunters/AcurusTrack/commit/1c60237654bd81f81b22aacdea4ccf94bb7f24b2

Let us know if you have succeeded!

**Comment by igormusinov** [comment]
It works. thank you
