### ISSUE TITLE
Person tracking without pose estimation

### ISSUE THREAD

**Issue by ogencoglu** [AIHunters/AcurusTrack#2]
Thanks for the nice work!

Can we use this library for person tracking with basic bounding box detection (e.g. plugging YOLOv4 or our custom detector) without having to use pose estimation? And if so, what would be needed to get it working?

**Comment by KseniaMeshkova** [comment]
Sure, you can do it. You should simply use json with your detections in a format that's described in README ({"frame_no": [{"x1": top_right_x, "y1": top_right_y, "x2": bottom_left_x, "y2": bottom_left_y}], "frame_no":[],...}) and make sure, that in config.py face_or_pose_meta = 'face'. And it's set like this anyway. This should work!
Feel free to ask any other questions you have!
