### ISSUE TITLE
Does it only support off-line tracking?

### ISSUE THREAD

**Issue by codylcs** [AIHunters/AcurusTrack#3]
Thanks for your amazing work,as question shown in the title,must i put json file off-line to track?

**Comment by vishneuskaja** [comment]
Hi! Thanks for the evaluation! We really appreciate your feedback.

1. In the case of online, there will be, obviously, real-time. The processing of a potential window will take less than its length even on a weak CPU.
2. Secondary, there will be some delays in decision-making. These delays will be determined by the length of a window. So this has to depend on the business case. In the case of online applications, the algorithm supports real-time processing. But the decision delay can make some of the cases impossible to handle.

3. Anyway, it's more a question of the realization that the algorithm itself. 
Hope I answered your question!

**Comment by vishneuskaja** [comment]
@codylcs did our answer help? Feel free to ask if there's something left unclear!

**Comment by codylcs** [comment]
sorry for replying late because of something,I had a solution of my project,thank u any way,good luck!!
