### ISSUE TITLE
AttributeError: 'TrackVisualization' object has no attribute 'homography_dict'

### ISSUE THREAD

**Issue by eeric** [AIHunters/AcurusTrack#4]
in visualization/make_video_with_meta.py 
python3 visualization/make_video_with_meta.py --video_path ../inference/images/exps.avi --files_dir ../results/outvideo1821/res/res/_947_1839
it occured error as following:
curr_file_info = fixed_to_original_coordinate_system(meta_dict, self.homography_dict,
                                                                     int(os.environ.get('fixed_coordinate_resize_h')),
                                                                     int(os.environ.get('fixed_coordinate_resize_w')),
                                                                     self.height,
                                                                     self.width)

how to set self.homography_dict?

**Comment by KseniaMeshkova** [comment]
If you have used the EvenVision component and have a file with the necessary transformations to switch to a fixed coordinate system, you can simply set this file as an argument path_to_homography_dict. And if you don't have such a file, you should check the code update - there we have added the ability to make visualizations without this file. But in such case the results of working with a moving camera can be unforeseen.
