### ISSUE TITLE
how to use result by run.py?

### ISSUE THREAD

**Issue by eeric** [AIHunters/AcurusTrack#9]
python3 run.py --detections ../2020/ppbbox.json --video_path ../inference/images/0601.avi --video_name outvideo1821 --exp_name res --start_frame 59

successfully run. how to use result about .csv or .json?

**Comment by KseniaMeshkova** [comment]
If you are interested in only the final result, you can find it in result.json file. There the detection boxes with the corresponding id-s obtained with AcurusTrack are saved. The other files are the result of the algorithm's work at different stages.
